apiVersion: v1
kind: ConfigMap
metadata:
  name: skubestore-configmap
data:
  MYSQL_HOST: mysql-service
  MYSQL_USER: skubestore
  MYSQL_DATABASE: skubestore
  VITE_BACKEND_URL:  https://api.skubestore.click
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-system-configmap
  namespace: kube-system
data:
  AWS_REGION: us-east-1
  HOSTED_ZONE_ID: Z05022711DDYB75JEHHOL

  