apiVersion: v1
kind: ConfigMap
metadata:
  name: skubestore-configmap
data:
  MYSQL_HOST: mysql-service
  MYSQL_USER: skubestore
  MYSQL_DATABASE: skubestore
  VITE_PRODUCT_SERVICE_URL: http://product-service:5000
  VITE_ORDER_SERVICE_URL: http://order-service:5000
  VITE_USER_SERVICE_URL: http://user-service:5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-system-configmap
  namespace: kube-system
data:
  AWS_REGION: us-east-1
  HOSTED_ZONE_ID: Z05022711DDYB75JEHHOL

  