apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: skubestore
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        tier: frontend
        framework: react
    spec:
      containers:
      - name: frontend-container
        image: noambenm/skubestore-frontend-service:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: VITE_BACKEND_INGRESS
            valueFrom:
              configMapKeyRef:
                name: skubestore-configmap
                key: VITE_BACKEND_INGRESS
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: skubestore
spec:
  type: NodePort
  selector:
      service: frontend
  ports:
  - port: 80
