apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: order
  template:
    metadata:
      labels:
        service: order
        tier: backend
        framework: flask
    spec:
      containers:
      - name: order-container
        image: noambenm/skubestore-order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: skubestore-configmap
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: skubestore-secret
                key: MYSQL_PASSWORD
      initContainers:
      - name: init-container
        image: noambenm/skubediver-divelog-init:v1.0-alpine3.20
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: skubestore-configmap
        - secretRef:
            name: skubestore-secret        
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
      service: order
  ports:
  - port: 5000
